// supabase/seed/data/*.json → supabase/seed.sql を生成する
// 実行: node supabase/seed/build-seed.mjs
// 生成された seed.sql は Supabase Dashboard > SQL Editor で実行する（schema.sql 実行後）。冪等（slug で upsert / 子テーブルは差し替え）。
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "data");
const out = join(here, "..", "seed.sql");

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const jq = (v) => (v === null || v === undefined ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`);

// シード用オーサー（AUTHORS.json が正。username から決定論的にUUIDを導出）
const AUTHORS = JSON.parse(await readFile(join(here, "AUTHORS.json"), "utf8")).authors;
const uidOf = (u) => "00000000-0000-4000-8000-" + createHash("md5").update(u).digest("hex").slice(0, 12);
const ownerBySlug = {};
for (const a of AUTHORS) for (const sl of a.timelines) ownerBySlug[sl] = uidOf(a.username);
const CHRONOS_UID = uidOf("chronos");
const exclamOK = new Set(AUTHORS.filter((a) => /「!」は感情が乗る箇所/.test(a.tone)).map((a) => uidOf(a.username)));

const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json")).sort();
const problems = [];
let sql = `-- Generated by supabase/seed/build-seed.mjs — ${files.length} timelines, ${AUTHORS.length} authors\n`;
sql += `-- 事前に schema.sql を実行していること。auth.users にシードユーザーを作れないため users.id の FK を満たす行を直接挿入する。\n`;
for (const a of AUTHORS) {
  const id = uidOf(a.username);
  sql += `insert into auth.users (id, email, raw_user_meta_data, created_at, updated_at, aud, role)
values ('${id}', '${a.username}@chronos.local', '{"seed":true}'::jsonb, now(), now(), 'authenticated', 'authenticated')
on conflict (id) do nothing;\n`;
  sql += `insert into public.users (id, username, display_name, bio, country, age_band)
values ('${id}', ${q(a.username)}, ${q(a.display_name)}, ${q(a.bio)}, 'JP', 'adult')
on conflict (id) do update set username = excluded.username, display_name = excluded.display_name, bio = excluded.bio;\n`;
}
sql += "\n";

for (const f of files) {
  const t = JSON.parse(await readFile(join(dataDir, f), "utf8"));
  // ---- 検証
  const layerNames = new Set(t.layers.map((l) => l.name));
  const colors = t.layers.map((l) => l.color);
  if (new Set(colors).size !== colors.length) problems.push(`${t.slug}: layer color duplicated`);
  for (const [i, e] of t.events.entries()) {
    if (!layerNames.has(e.layer)) problems.push(`${t.slug}#${i}: unknown layer "${e.layer}"`);
    if (e.type === "period" && (!e.end_date || e.end_date < e.date)) problems.push(`${t.slug}#${i}: bad period`);
    if ((e.credibility === "disputed" || e.credibility === "unverified") && !e.credibility_note)
      problems.push(`${t.slug}#${i}: note required for ${e.credibility}`);
    // 「!」はペルソナ許可制（AUTHORS.json の tone に明記されたオーサーのみ）。titleは常に禁止
    if (/[!！]/.test(e.title)) problems.push(`${t.slug}#${i}: "!" in title`);
    if (/[!！]/.test(`${e.summary}${e.detail ?? ""}`) && !exclamOK.has(ownerBySlug[t.slug]))
      problems.push(`${t.slug}#${i}: "!" by author without permission`);
  }
  const years = t.events.map((e) => +e.date.slice(0, 4));
  const startYear = t.start_year ?? Math.min(...years);
  const endYear = t.end_year ?? Math.max(...years);

  sql += `-- ═══ ${t.slug} — ${t.title}\n`;
  if (!ownerBySlug[t.slug]) problems.push(`${t.slug}: no author assigned (falls back to @chronos)`);
  sql += `insert into public.timelines (slug, owner_id, title, description, category, language, visibility, share_id, start_year, end_year, cover_seed)
values (${q(t.slug)}, '${ownerBySlug[t.slug] || CHRONOS_UID}', ${q(t.title)}, ${q(t.description)}, ${q(t.category)}, ${q(t.language ?? "ja")}, 'public', ${q("s_" + t.slug)}, ${startYear}, ${endYear}, ${q(t.slug)})
on conflict (slug) do update set owner_id = excluded.owner_id, title = excluded.title, description = excluded.description, category = excluded.category,
  start_year = excluded.start_year, end_year = excluded.end_year, updated_at = now();\n`;
  // 子テーブルは差し替え
  sql += `delete from public.layers where timeline_id = (select id from public.timelines where slug = ${q(t.slug)});\n`;
  sql += `delete from public.events where timeline_id = (select id from public.timelines where slug = ${q(t.slug)});\n`;
  t.layers.forEach((l, i) => {
    sql += `insert into public.layers (timeline_id, name, color, position) values ((select id from public.timelines where slug = ${q(t.slug)}), ${q(l.name)}, ${q(l.color)}, ${i});\n`;
  });
  t.events.forEach((e, i) => {
    sql += `with ev as (insert into public.events (timeline_id, layer_id, event_date, end_date, date_precision, event_type, title, summary, detail, credibility, credibility_note, origin, position)
  values ((select id from public.timelines where slug = ${q(t.slug)}),
          (select id from public.layers where timeline_id = (select id from public.timelines where slug = ${q(t.slug)}) and name = ${q(e.layer)}),
          ${q(e.date)}, ${q(e.end_date ?? null)}, ${q(e.precision ?? "day")}, ${q(e.type ?? "point")}, ${q(e.title)}, ${q(e.summary)}, ${q(e.detail ?? null)},
          ${q(e.credibility ?? "unverified")}, ${q(e.credibility_note ?? null)}, 'user', ${i}) returning id)\n`;
    const srcs = (e.sources ?? []).filter((s) => s && s.title);
    if (srcs.length) {
      sql += `insert into public.event_sources (event_id, title, url) select ev.id, v.title, v.url from ev, (values ${srcs.map((s) => `(${q(s.title)}, ${q(s.url ?? null)})`).join(", ")}) as v(title, url);\n`;
    } else {
      sql += `select 1 from ev;\n`;
    }
  });
  sql += "\n";
}

await writeFile(out, sql);
console.log(`seed.sql: ${files.length} timelines -> ${out}`);
if (problems.length) {
  console.log(`VALIDATION WARNINGS (${problems.length}):`);
  for (const p of problems) console.log("  - " + p);
}
