// supabase/seed/data/*.json → supabase/seed.sql を生成する
// 実行: node supabase/seed/build-seed.mjs
// 生成された seed.sql は Supabase Dashboard > SQL Editor で実行する（schema.sql 実行後）。冪等（slug で upsert / 子テーブルは差し替え）。
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "data");
const out = join(here, "..", "seed.sql");

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const jq = (v) => (v === null || v === undefined ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`);

// シード用のデモオーナー（公開プロフィール @chronos として表示）
const DEMO_USER = {
  id: "00000000-0000-4000-8000-000000000001",
  username: "chronos",
  display_name: "Chronos 編集部",
  bio: "公式のサンプル年表です。出典と信憑性ラベルを確認しながらお読みください。",
};

const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json")).sort();
const problems = [];
let sql = `-- Generated by supabase/seed/build-seed.mjs — ${files.length} timelines\n`;
sql += `-- 事前に schema.sql を実行していること。auth.users にデモユーザーを作れないため users.id の FK を一時的に満たす行を直接挿入する。\n`;
sql += `insert into auth.users (id, email, raw_user_meta_data, created_at, updated_at, aud, role)
values ('${DEMO_USER.id}', 'seed@chronos.local', '{"seed":true}'::jsonb, now(), now(), 'authenticated', 'authenticated')
on conflict (id) do nothing;\n`;
sql += `insert into public.users (id, username, display_name, bio, country, age_band)
values ('${DEMO_USER.id}', ${q(DEMO_USER.username)}, ${q(DEMO_USER.display_name)}, ${q(DEMO_USER.bio)}, 'JP', 'adult')
on conflict (id) do update set display_name = excluded.display_name, bio = excluded.bio;\n\n`;

for (const f of files) {
  const t = JSON.parse(await readFile(join(dataDir, f), "utf8"));
  // ---- 検証
  const layerNames = new Set(t.layers.map((l) => l.name));
  const colors = t.layers.map((l) => l.color);
  if (new Set(colors).size !== colors.length) problems.push(`${t.slug}: layer color duplicated`);
  for (const [i, e] of t.events.entries()) {
    if (!layerNames.has(e.layer)) problems.push(`${t.slug}#${i}: unknown layer "${e.layer}"`);
    if (e.type === "period" && (!e.end_date || e.end_date < e.date)) problems.push(`${t.slug}#${i}: bad period`);
    if ((e.credibility === "disputed" || e.credibility === "unverified") && !e.credibility_note)
      problems.push(`${t.slug}#${i}: note required for ${e.credibility}`);
    if (/[!！]/.test(`${e.title}${e.summary}${e.detail ?? ""}`)) problems.push(`${t.slug}#${i}: contains "!"`);
  }
  const years = t.events.map((e) => +e.date.slice(0, 4));
  const startYear = t.start_year ?? Math.min(...years);
  const endYear = t.end_year ?? Math.max(...years);

  sql += `-- ═══ ${t.slug} — ${t.title}\n`;
  sql += `insert into public.timelines (slug, owner_id, title, description, category, language, visibility, share_id, start_year, end_year, cover_seed)
values (${q(t.slug)}, '${DEMO_USER.id}', ${q(t.title)}, ${q(t.description)}, ${q(t.category)}, ${q(t.language ?? "ja")}, 'public', ${q("s_" + t.slug)}, ${startYear}, ${endYear}, ${q(t.slug)})
on conflict (slug) do update set title = excluded.title, description = excluded.description, category = excluded.category,
  start_year = excluded.start_year, end_year = excluded.end_year, updated_at = now();\n`;
  // 子テーブルは差し替え
  sql += `delete from public.layers where timeline_id = (select id from public.timelines where slug = ${q(t.slug)});\n`;
  sql += `delete from public.events where timeline_id = (select id from public.timelines where slug = ${q(t.slug)});\n`;
  t.layers.forEach((l, i) => {
    sql += `insert into public.layers (timeline_id, name, color, position) values ((select id from public.timelines where slug = ${q(t.slug)}), ${q(l.name)}, ${q(l.color)}, ${i});\n`;
  });
  t.events.forEach((e, i) => {
    sql += `with ev as (insert into public.events (timeline_id, layer_id, event_date, end_date, date_precision, event_type, title, summary, detail, credibility, credibility_note, origin, position)
  values ((select id from public.timelines where slug = ${q(t.slug)}),
          (select id from public.layers where timeline_id = (select id from public.timelines where slug = ${q(t.slug)}) and name = ${q(e.layer)}),
          ${q(e.date)}, ${q(e.end_date ?? null)}, ${q(e.precision ?? "day")}, ${q(e.type ?? "point")}, ${q(e.title)}, ${q(e.summary)}, ${q(e.detail ?? null)},
          ${q(e.credibility ?? "unverified")}, ${q(e.credibility_note ?? null)}, 'user', ${i}) returning id)\n`;
    const srcs = (e.sources ?? []).filter((s) => s && s.title);
    if (srcs.length) {
      sql += `insert into public.event_sources (event_id, title, url) select ev.id, v.title, v.url from ev, (values ${srcs.map((s) => `(${q(s.title)}, ${q(s.url ?? null)})`).join(", ")}) as v(title, url);\n`;
    } else {
      sql += `select 1 from ev;\n`;
    }
  });
  sql += "\n";
}

await writeFile(out, sql);
console.log(`seed.sql: ${files.length} timelines -> ${out}`);
if (problems.length) {
  console.log(`VALIDATION WARNINGS (${problems.length}):`);
  for (const p of problems) console.log("  - " + p);
}
